const GET_POKEMONS_START = 'GET_POKEMONS_START';
const GET_POKEMONS_SUCCESS = 'GET_POKEMONS_SUCCESS';
const GET_POKEMONS_FAILURE = 'GET_POKEMONS_FAILURE';

export { GET_POKEMONS_START, GET_POKEMONS_SUCCESS, GET_POKEMONS_FAILURE };
