const GET_POKEMONS_START = 'GET_POKEMONS_START';
const GET_POKEMONS_SUCCESS = 'GET_POKEMONS_SUCCESS';
const GET_POKEMONS_FAILURE = 'GET_POKEMONS_FAILURE';

const GET_POKEMON_START = 'GET_POKEMON_START';
const GET_POKEMON_SUCCESS = 'GET_POKEMON_SUCCESS';
const GET_POKEMON_FAILURE = 'GET_POKEMON_FAILURE';

export {
  GET_POKEMONS_START,
  GET_POKEMONS_SUCCESS,
  GET_POKEMONS_FAILURE,
  GET_POKEMON_START,
  GET_POKEMON_SUCCESS,
  GET_POKEMON_FAILURE,
};
