const GET_POKEMONS_START = 'GET_POKEMONS_START';
const GET_POKEMONS_SUCCESS = 'GET_POKEMONS_SUCCESS';
const GET_POKEMONS_FAILURE = 'GET_POKEMONS_FAILURE';

const GET_POKEMON_START = 'GET_POKEMON_START';
const GET_POKEMON_SUCCESS = 'GET_POKEMON_SUCCESS';
const GET_POKEMON_FAILURE = 'GET_POKEMON_FAILURE';

const ADD_POKEMON = 'ADD_POKEMON';

const RELEASE_POKEMON = 'RELEASE_POKEMON';
const RELEASE_ALL_POKEMON = 'RELEASE_ALL_POKEMON';

export {
  GET_POKEMONS_START,
  GET_POKEMONS_SUCCESS,
  GET_POKEMONS_FAILURE,
  GET_POKEMON_START,
  GET_POKEMON_SUCCESS,
  GET_POKEMON_FAILURE,
  ADD_POKEMON,
  RELEASE_POKEMON,
  RELEASE_ALL_POKEMON,
};
